# -*- coding: utf-8 -*-
"""Sparks_Task#6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10x1OnWKAnBONt2qut7-3srgnC2SPrPEs

# Name: Yashwant Gawkar
**Sparks Foundation Data Science Intern Task #6 ||
 Prediction Using Decision Tree Algorithm**
"""

import pandas as pd

data=pd.read_csv("https://raw.githubusercontent.com/yashwant-gawkar/Sparks_Foundation_Task_6/main/Iris.csv")


print("Data imported successfully")
print("DATA:")
data

data.shape

x=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

print("First 10 records of x:\n",x[0:10],"\n")
print("First 10 records of y:\n",y[0:10])

from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x,y)

!pip install pydotplus
!apt-get install graphviz -y

from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus


dot_data = StringIO()
export_graphviz(dtree, out_file=dot_data, feature_names=iris.feature_names,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

X_test=[[5.1,3.5,100,0.2],[6.7	,3.0	,1,2.3]]
y_pred = dtree.predict(X_test)
print("We can classify what will be the species using the various inputs as:")
for i in range(2):
  print(X_test[i],"gives an output as",y_pred[i])

